### PR TITLE
Test config with ocvalidate

### PR DESCRIPTION
**Pull request by brokeyourbike**
This is not documentation or configuration change. 

I have added CI to test config with ocvalidate.

### CODE REVIEW

**Review by UHDbits — CHANGES_REQUESTED** [review]
Thanks for your pull request, this is actually quite a useful feature that I never thought of. I usually self-validate any configuration changes that I make, but of course, it's always possible for things to slip through the cracks. 

There are a couple of changes that I would personally add before merging this into main, but these are fairly minor, and I can likely add them by myself in the next week or so, unless you would like to add them now.

1. Only run when the "EFI" folder is changed. I make lots of documentation changes, so this would remove unneeded Actions running when it isn't needed. This could be done using some info from [here](https://stackoverflow.com/questions/63822219/how-to-run-github-actions-workflow-only-if-the-pushed-files-are-in-a-specific-fo).
2. Also run when pushed to the "legacy" branch. This probably isn't needed, because I don't plan to heavily maintain the legacy branch in the near future, but it would just be a nice to have.

Once again, thanks for your pull request! I will merge it into main once those changes above are made, either by you or me, and it's fine if you don't make them, they are fairly minor and won't take me long. Thanks again!

**Comment by UHDbits** [comment]
You can also change the Action to specify OC 0.9.2 since the configuration has now been updated, but that's an extremely easy change for me to make. I'll also add a new comment if there are any other changes that I think need to be made, but anymore changes will likely just be made by me.

**Comment by brokeyourbike** [comment]
Great to hear that you consider this PR useful @UHDbits. I have pushed a commit to address your comments, please take a look.

**Comment by UHDbits** [comment]
Once again, thanks for your helpful commit! Very appreciated!

**Pull request merged**
